### ISSUE TITLE
Toggl API due to rebrand, domains being dropped for API June 30th 2021 use api.track.toggl.com ASAP

### ISSUE THREAD

**Issue by LiamKarlMitchell** [LiamKarlMitchell/toggl_active_collab_bridge#13]
https://github.com/7eggs/node-toggl-api/issues/17

In node-toggl-api in /lib/client.js replace:
```
  apiUrl: 'https://www.toggl.com',
  reportsUrl: 'https://www.toggl.com/reports'
```
To:

~~apiUrl: 'https://track.toggl.com',~~
~~reportsUrl: 'https://track.toggl.com/reports'~~

```
apiUrl: 'https://api.track.toggl.com',
reportsUrl: 'https://api.track.toggl.com/reports'
```

**Comment by gilberthdez** [comment]
please check the official docs https://github.com/toggl/toggl_api_docs/blob/master/toggl_api.md the correct urls are https://api.track.toggl.com and https://api.track.toggl.com/reports

**Comment by LiamKarlMitchell** [comment]
Thanks @gilberthdez

**Comment by LiamKarlMitchell** [comment]
https://github.com/toggl/toggl_api_docs/issues/411

**Comment by LiamKarlMitchell** [comment]
Hi there, 

We are reaching out because we detected your Toggl Track API usage coming to the www.toggl.com(or toggl.com) domain. 

If you (or your company) have developed a custom integration, we want to remind you that the usage of www.toggl.com (or toggl.com) domains for the API will be dropped after 'June 30th 2021'. 

We encourage you to perform the switch to api.track.toggl.com as soon as possible in order to prevent disruption. Please check the official API Documentation for any extra info. 

Best wishes, 
The Toggl Track Team 
support@track.toggl.com

**Comment by LiamKarlMitchell** [comment]
For now work-around would be to make a patch-package.
https://dev.to/zhnedyalkow/the-easiest-way-to-patch-your-npm-package-4ece

**Comment by TheTechmo** [comment]
./MyTogglClient.js

Modify TogglClient:
```
const toggl = new TogglClient({
        apiToken: config.Toggl.token,
        apiUrl: "https://api.track.toggl.com",
        reportsUrl: "https://api.track.toggl.com/reports"
})
```

**Comment by LiamKarlMitchell** [comment]
We currently have a patch-package for the Toggl API dependency.
This changes the URL's, but did not appear to work on some deployments.

Yes it would be best to configure and passed to it from the MyToggl.js

https://dev.to/zhnedyalkow/the-easiest-way-to-patch-your-npm-package-4ece

```npm install patch-package -D```

To manually patch the package you should run this, but it should happen post install.
```npx patch-package```
